spring:
    datasource:
        name: xstgongyi
        url: jdbc:mysql://127.0.0.1/xstgongyi?useUnicode=true
        username: dbadmin
        password: dbadminpass
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
     org.xstgongyi.eduaid.masterdata.dao: debug

# 修改jsp无需重新启动，prod环境请勿使用（仅用于Run as Application启动方式）
#server.servlet.jsp.init-parameters.development: true
